stages:
  - build

build:
  stage: build
  image: rust:latest
  before_script:
  - export PATH="$HOME/.cargo/bin:$PATH"
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/my_binary